language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: 76a05c1f-bae0-4949-97c3-d82de3372db0
    app: chester-todo-app
